enum AddressingMode {
  unused,
  modeAbsolute,
  modeAbsoluteX,
  modeAbsoluteY,
  modeAccumulator,
  modeImemdiate,
  modeImplied,
  modeIndexedIndirect,
  modeIndirect,
  modeIndirectIndexed,
  modeRelative,
  modeZeroPage,
  modeZeroPageX,
  modeZeroPageY,
}
